model_list:
  - model_name: Qwen3-VL-30B-A3B-Thinking
    litellm_params:
      model: hosted_vllm/Qwen3-VL-30B-A3B-Thinking
      api_base: http://localhost:8000/v1
      api_key: EMPTY
  - model_name: Qwen3-VL-30B-A3B-Thinking
    litellm_params:
      model: hosted_vllm/Qwen3-VL-30B-A3B-Thinking
      api_base: http://localhost:8001/v1
      api_key: EMPTY
  - model_name: Qwen3-VL-30B-A3B-Thinking
    litellm_params:
      model: hosted_vllm/Qwen3-VL-30B-A3B-Thinking
      api_base: http://localhost:8002/v1
      api_key: EMPTY
  - model_name: Qwen3-VL-30B-A3B-Thinking
    litellm_params:
      model: hosted_vllm/Qwen3-VL-30B-A3B-Thinking
      api_base: http://localhost:8003/v1
      api_key: EMPTY
  - model_name: Qwen3-VL-30B-A3B-Thinking
    litellm_params:
      model: hosted_vllm/Qwen3-VL-30B-A3B-Thinking
      api_base: http://localhost:8004/v1
      api_key: EMPTY
  - model_name: Qwen3-VL-30B-A3B-Thinking
    litellm_params:
      model: hosted_vllm/Qwen3-VL-30B-A3B-Thinking
      api_base: http://localhost:8005/v1
      api_key: EMPTY
  # - model_name: Qwen3-VL-30B-A3B-Thinking
  #   litellm_params:
  #     model: hosted_vllm/Qwen3-VL-30B-A3B-Thinking
  #     api_base: http://localhost:8006/v1
  #     api_key: EMPTY
  - model_name: Qwen3-VL-30B-A3B-Thinking
    litellm_params:
      model: hosted_vllm/Qwen3-VL-30B-A3B-Thinking
      api_base: http://localhost:8007/v1
      api_key: EMPTY
